### ISSUE TITLE
Download artifacts from an authenticated Maven repo

### ISSUE THREAD

**Issue by green-coder** [sebersole/gradle-maven-publish-auth#10]
Is this plugin suitable for _downloading_ artifacts from an authenticated Maven repo, whose credentials are specified in the file `~/.m2/settings.xml`? If no, then please consider this issue as a feature request.

**Comment by wsh** [comment]
I need this. :smile: I'm going to try to implement it.

**Comment by bszeliga** [comment]
+1

**Comment by wsh** [comment]
Okay, so the crappy solution is:
```
import org.hibernate.build.gradle.publish.auth.maven.CredentialsProviderRegistry

def loadMavenCreds(String repositoryId) {
    return new CredentialsProviderRegistry().providers().asList().stream()
        .map { p -> p.determineAuthentication(repositoryId) }
        .findAny()
        .orElseThrow(ofInstance(new RuntimeException("Maven authorization missing")))
}

def creds = loadMavenCreds("YOUR_REPO_HERE")

maven {
    credentials {
        username creds.getUserName()
        password creds.getPassword()
    }
    url = 'YOUR_REPO_HERE'
}
```
This works for me, but I'd love to make it elegant. I'm still a total Gradle novice, though.

**Comment by sebersole** [comment]
https://plugins.gradle.org/plugin/org.hibernate.build.maven-repo-auth/3.0.0
