### ISSUE TITLE
plugin must be applied *after* uploadArchives.repositories section is defined

### ISSUE THREAD

**Issue by dlethin** [sebersole/gradle-maven-publish-auth#15]
I've used your plugin successfully on one project and I was trying to use it on another project, but I was having trouble getting the second project to work.  I finally tracked down the issue.

If my build.gradle file looks like this:

apply plugin: 'maven-publish-auth'

uploadArchives {
    repositories.mavenDeployer {
        ...
        repository(id: 'dogdeball-repo', url: 'http://repository.average.joes.com')
    }
}

When I try to run the gradle uploadArchives, it fails with a 401 unauthorized error.

However, if I change the order of my build.gradle file to only apply the plugin _after_ the repositories definition is set like this:

uploadArchives {
    repositories.mavenDeployer {
        ...
        repository(id: 'dogdeball-repo', url: 'http://repository.average.joes.com')
    }
}

apply plugin: 'maven-publish-auth'

It works fine.

I didn't see anything in the documentation suggesting that these things have to be ordered this way.  I would think there should not be a dependency on order.

Thanks.

**Comment by sebersole** [comment]
The release I just did should fix this.  https://plugins.gradle.org/plugin/org.hibernate.build.maven-repo-auth/3.0.0
