### ISSUE TITLE
Known issue with plugin and gradle 1.12 and higher?

### ISSUE THREAD

**Issue by dlethin** [sebersole/gradle-maven-publish-auth#17]
I've been using this plugin with a gradle 1.11 distribution.  I just tried to upgrade my project to use the latest gradle 2.2.1 and when attempting to publish to our local maven repo using this plugin, I get a http 401 error.   I then tried subsequent versions of gradle.  1.11 appears to be the last working version.  1.12 does not.  Can't seem to find anything obvious in the release notes of 1.12 to suggest why its not working.

I'm using the old-style maven publish and JDK 7

Thanks.

Doug

**Comment by sebersole** [comment]
Going to close this as out of date.
