### ISSUE TITLE
Plugin shouldn't use static state

### ISSUE THREAD

**Issue by melix** [sebersole/gradle-maven-publish-auth#19]
A Gradle user reported to me that he had to kill the Gradle daemon for changes in `settings.xml` to be visible. He explained to me he was using this plugin, so I immediately suspected a static field.

After a quick inspection I found this: https://github.com/sebersole/gradle-maven-publish-auth/blob/6a77779e32073dada313b8e3bb9c609b535c13d9/src/main/java/org/hibernate/build/gradle/publish/auth/maven/SettingsXmlCredentialsProvider.java#L54

This is problematic in Gradle, because this field will survive across builds when running with the daemon.

**Comment by sebersole** [comment]
Finally figured out how to test this and ran into this problem running tests.  Just fixed in 3.0.0 - https://plugins.gradle.org/plugin/org.hibernate.build.maven-repo-auth/3.0.0
