### ISSUE TITLE
Download of project dependencies failes when using a (NTLM) proxy

### ISSUE THREAD

**Issue by Eckaaaaaat** [sebersole/gradle-maven-publish-auth#26]
When this plugin is enabled and I use and NTLM proxy (or maybe any other proxy which requires authentication) I can't download project dependencies. 

For full stacktrace of sample see [gradle_error.txt](https://github.com/sebersole/gradle-maven-publish-auth/files/4197714/gradle_error.txt)

I tried to configure a diffrent proxy which doesn't need authentication but I still got this error. As workaround I have to disable the plugin to download dependencies and then reenable it.

**Comment by sebersole** [comment]
I'm happy to review and apply any changes you think fixes the problem.  If you do, create a PR.  Thanks
