### ISSUE TITLE
Version 3.0.1 compiled to Java 11 target

### ISSUE THREAD

**Issue by coyotesqrl** [sebersole/gradle-maven-publish-auth#28]
This might be intentional and therefore just require a note in the README, but the just-released version 3.0.1 of the plugin has been compiled to class file version 55.0 and no longer works with Java 8 projects.

I suspect and hope it was not intentional or many of my projects will be stuck on version 3.0.0.

**Comment by sebersole** [comment]
Yes that was just an oversight.  Still setting up a new machine and just missed that

**Comment by sebersole** [comment]
Just published 3.0.2 which should fix that

**Comment by sebersole** [comment]
I'll assume it was fixed as I have not heard back.

**Comment by coyotesqrl** [comment]
Sorry. I forgot to comment back. It's good now. Thanks!

**Comment by sebersole** [comment]
No problem.  Just trying to keep the issues/prs clean.  Thanks for letting
me know
