### ISSUE TITLE
2.0.x has broken support for the old publishing plugin

### ISSUE THREAD

**Issue by szpak** [sebersole/gradle-maven-publish-auth#7]
I'm unable to make gradle-maven-publish-auth 2.0.1 (also 2.0.0) work with the old publishing plugin (I tested my configuration with 1.1.1 and worked fine). In the build log I see that my servers from settings.xml was detected, but while debuging it looks like a wagon doesn't have username and password set (there are null). Your plugin works fine with the new publishing plugin, but I have to switch back to the old one to handle artifact signing on upload.

**Comment by sebersole** [comment]
Legacy publishing support should work in new version - https://plugins.gradle.org/plugin/org.hibernate.build.maven-repo-auth/3.0.0

**Comment by szpak** [comment]
Thanks :).
